<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>TS_Login_MakeAppointment_Setup_TearDown</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>005668ce-6546-49c4-89df-52bf5c04eaa7</testSuiteGuid>
   <testCaseLink>
      <guid>c341c448-3da6-4eec-9e97-5da9f971e978</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/TC_CHS_Login/TC_CHS_Login_001</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>261f9d89-9a4a-4dc1-8a4c-b29563e12818</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/CHS_Excel_TestData_Login/Login_ExcelData</testDataId>
      </testDataLink>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>b6bf32ac-7fed-4a1f-a80d-d283fff8e829</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/CHS_Internal_Date_MakeAppointment/MakeAppointment_Internal_Data</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>261f9d89-9a4a-4dc1-8a4c-b29563e12818</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>username</value>
         <variableId>092ea4ee-633a-41f1-ae76-2e0dbb492109</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>261f9d89-9a4a-4dc1-8a4c-b29563e12818</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>password</value>
         <variableId>1c191c30-a365-417c-b6f8-6ff2bee49e6a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>914ed3d3-b1bd-4e1e-b858-f2a0c00a3dc7</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/TC_CHS_MakeAppointment/TC_CHS_MakeAppointement_002</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>56885c04-fa20-4d49-97eb-19baa1c41017</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fbbc7cc1-df37-4d6c-846d-7a866a383b52</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
