<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Logout_Internal_Data</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>beaa1d57-0b58-4fa3-a5ef-ed1134fa4926</testSuiteGuid>
   <testCaseLink>
      <guid>13d0c1fc-1523-45f6-ac95-8918e82dc97f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC_CHS_Logout/TC_CHS_Logout_004</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>55763716-f7a8-4558-8090-476037df317c</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/CHS_Logout_Internal_Data/Logout_Internal_Data</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>55763716-f7a8-4558-8090-476037df317c</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>username</value>
         <variableId>359ad2a5-2ede-4376-a64e-e5a8623e662c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>55763716-f7a8-4558-8090-476037df317c</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>password</value>
         <variableId>d93da0f5-35b7-4e5e-b86b-4a2224f33c78</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
