<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>TListener_CHS_MakeAppointment</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>53645fc0-9e6a-481a-8c0e-65456149e079</testSuiteGuid>
   <testCaseLink>
      <guid>a1a36f43-30de-4236-82df-5f031ebc213e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC_CHS_MakeAppointment/TC_CHS_MakeAppointement_002</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>a069f7d8-b2bd-4698-8543-c9fbf6548aaa</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/CHS_Internal_Date_MakeAppointment/MakeAppointment_Internal_Data</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>a069f7d8-b2bd-4698-8543-c9fbf6548aaa</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>facility</value>
         <variableId>56885c04-fa20-4d49-97eb-19baa1c41017</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>a069f7d8-b2bd-4698-8543-c9fbf6548aaa</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>date</value>
         <variableId>fbbc7cc1-df37-4d6c-846d-7a866a383b52</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
